services:
    sibers_api.responce_listener:
        class: Sibers\ApiBundle\EventListener\ResponseEventListener
        arguments: [ '@sibers_api.error_handler']
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    sibers_api.request_subscriber:
        class: Sibers\ApiBundle\EventListener\RequestEventSubscriber
        tags:
            - { name: kernel.event_subscriber }

    sibers_api.exception_subscriber:
        class: Sibers\ApiBundle\EventListener\ApiExceptionSubscriber
        arguments: [ '@sibers_api.error_handler']
        tags:
            - { name: kernel.event_subscriber, event: kernel.exception }